[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov-config=.coveragerc --cov=grplot --cov-report term-missing --cov-report html"
testpaths = [
    "tests"
]